Begonia 106 exporter changes
vmware-tanzu/cloud-native-security-inspector pull request #218
Opened 2023-03-15 07:16 UTC by snootan

Added governor exporter in new CNSI architecture.
Added permission for default service-account to read/write secret in cnsi-system namespace.

## Tests
1) Successfully getting telemetry data from new consumer governor in exporter:
<img width="1728" alt="Screenshot 2023-03-15 at 12 43 38 PM" src="https://user-images.githubusercontent.com/122356562/225233855-d29d9c21-071a-4220-b69f-b6ed7246ae6f.png">
2) No data in case of no namespace got scanned:
<img width="1728" alt="Screenshot 2023-03-15 at 12 45 10 PM" src="https://user-images.githubusercontent.com/122356562/225234139-5fe6be75-9f52-43f2-971d-c1397017f7eb.png">

2023-03-15 10:16 UTC, bgubbala requested changes

2023-03-15 10:16 UTC, bgubbala commented on src/pkg/exporter/outputs/governor.go
> +	exportReportToGovernor(&workloadReport, &c.Config.Governor)
check error from exportReportToGovernor

2023-03-15 10:16 UTC, bgubbala commented on src/pkg/exporter/cmd/main.go
> +		governorClient, err := outputs.NewClient(
This is HTTP Client. None of the methods w.r.t this client is not valid for Governor.
We can directly call GovernorPost or initialize Governor Client from here, we no need to map GovernorPost to the same client structure.

2023-03-15 10:16 UTC, bgubbala commented on src/pkg/exporter/outputs/governor/exporter.go
> +			kubernetesWorkloads.Replicas = workloadAssessment.Workload.Replicas
Please remove replica changes

2023-03-15 10:16 UTC, bgubbala commented on src/pkg/exporter/outputs/governor.go
> +func (c *Client) GovernorPost(payloadStr string) {
No need to add GovernorPost to Client Struct.

2023-03-15 10:52 UTC, snootan commented on src/api/v1alpha1/inspectionpolicy_types.go
> +	Enabled bool `json:"enabled"`
You have already raised one PR with all these changes. So it would not required to do changes here. It will take it after rebase.

2023-03-16 05:38 UTC, harshsharma071988 commented on src/pkg/exporter/cmd/main.go
> +		log.Error("Either URL or ClusterID or CSPSecretName is empty")
Dont log error, instead we can simply go to else part. Suppose someone is working on openSearch, they would see this unwanted error.
Ex: 
  ``` 
  if config.Governor.URL != "" && config.Governor.ClusterID != "" && config.Governor.CspSecretName != "" {
    // Do governor stuff
  }

2023-03-16 11:14 UTC, harshsharma071988 commented
LGTM

2023-03-17 06:39 UTC, 4everming approved these changes
LGTM

2023-03-17 07:12 UTC, bgubbala approved these changes

2023-03-17 07:15 UTC, bgubbala commented
Looks like the diff is updated. Just rebase the PR

2023-03-17 07:17 UTC, merged